# +-------------------------------------------------------------------------------------+
# | gremlin - PyFryLabs -> @pyfryday | darth.data410@gmail.com                          |
# | -------                                                                             |
# | register.py is a python module for the gremlin app that wraps the JSON register doc |
# | that a PseudoActor sends to an Actor to register with and await manuscript & acts.  |
# | (part of /meta)                                                                     |
# +-------------------------------------------------------------------------------------+
# | Apache License v2.0
# |$>

import json
import dataclasses as dc

#"PseudoActor": "<uuid generated by PseudoActor, which becomes PseudoActor ID with Parent Actor>",
#"RegisterNow": "YY-MM-DD~HH::MM::SS timstamp when registeration JSON generated",
#"Host": "<ip address of host>",
#"Port": "<listening port, awaiting manuscript & acts to perform>"

PSDACT="PseudoActor"
REGNOW="RegisterNow"
HOST="Host"
PORT="Port"

@dc.dataclass
class reginfo:
    """ for use with conversion between python objects/JSON. acts as a data contract """
    PseudoActor: str
    RegisterNow: str
    Host: str
    Port: int

    def fromjson(jsonobj):
        ljo = json.loads(jsonobj)
        ret = reginfo(
            PseudoActor=ljo[PSDACT],
            RegisterNow=ljo[REGNOW],
            Host=ljo[HOST],
            Port=ljo[PORT]
        )
        return ret
    
    def new(PseudoActor,RegisterNow,Host,Port):
        ret = reginfo(
            PseudoActor=PseudoActor,
            RegisterNow=RegisterNow,
            Host=Host,
            Port=Port
        )
        return ret

    def tojson(self):
        d = dict()
        d[PSDACT] = self.PseudoActor
        d[REGNOW] = self.RegisterNow
        d[HOST] = self.Host
        d[PORT] = self.Port
        ret = json.dumps(d)
        return ret


# example usgae:
if __name__=="__main__":
    rdc = reginfo(
        PseudoActor="test1",
        RegisterNow="ux00-yu-12-345-ght7",
        Host="127.0.0.1",
        Port=41013
    )    

    jsonobj = rdc.tojson()
    print(jsonobj)
    nrdc = reginfo.fromjson(jsonobj)
    print(nrdc)